<?php declare(strict_types=1);

/** Generated by Latte 3.1.4 */

use Latte\Runtime as LR;

/** source: auth/register */
final class Template_4f5f6545b7 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['message' => '10'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'web::layouts/main';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="mx-auto max-w-md px-6 py-16">
    <div class="rounded-xl border border-line bg-white p-8 shadow-sm">
        <h1 class="text-2xl font-bold">Create your account</h1>
        <p class="mt-2 text-sm text-muted">Start planning your marketing campaigns today.</p>

';
		if (isset($flash) && count($flash) > 0) /* pos 9:9 */ {
			foreach ($flash as $message) /* pos 10:13 */ {
				echo '                <div class="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">
                    ';
				echo LR\HtmlHelpers::escapeText($message) /* pos 12:21 */;
				echo '
                </div>
';

			}

		}
		echo '
        <form action="/register" method="post" class="mt-6 space-y-4">
            <input type="hidden" name="_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', $csrf_token) /* pos 18:56 */;
		echo '>
            <div>
                <label for="name" class="block text-sm font-semibold">Full name</label>
                <input id="name" name="name" type="text" required class="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm focus:border-blue focus:outline-none focus:ring-1 focus:ring-blue">
            </div>
            <div>
                <label for="email" class="block text-sm font-semibold">Email</label>
                <input id="email" name="email" type="email" required class="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm focus:border-blue focus:outline-none focus:ring-1 focus:ring-blue">
            </div>
            <div>
                <label for="password" class="block text-sm font-semibold">Password</label>
                <input id="password" name="password" type="password" required minlength="8" class="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm focus:border-blue focus:outline-none focus:ring-1 focus:ring-blue">
            </div>
            <button type="submit" class="w-full rounded-lg bg-ink px-4 py-2.5 text-sm font-bold text-white hover:bg-ink/90">Create account</button>
        </form>

        <p class="mt-6 text-center text-sm text-muted">
            Already have an account? <a href="/login" class="font-semibold text-ink hover:underline">Log in</a>
        </p>
    </div>
</section>
';
	}
}
